### ISSUE TITLE
Readme issue

### ISSUE THREAD

**Issue by flyingBear66** [alejouribesanchez/ScrollHideNavigationController#1]
#Hello @alejouribesanchez, 

Firstly thanks for the objective-c version. 

I was checking this new repo and there is a typo in readme :). Maybe you like that and added twice :D.

**AMScrollingNavbar**
TLYShyNavBar
BLKFlexibleHeightBar
**AMScrollingNavbar**
GTScrollNavigationBar
JKAutoShrinkView
SherginScrollableNavigationBar

**Comment by alejouribesanchez** [comment]
@flyingBear66 thanks I will fix it, give me a start :D

**Comment by alejouribesanchez** [comment]
Fixed
